# Generated by Django 3.1.5 on 2021-01-14 20:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserTable',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('empid', models.CharField(max_length=100, unique=True)),
                ('emp_name', models.CharField(max_length=100)),
                ('email_id', models.CharField(max_length=100, unique=True)),
                ('password', models.CharField(max_length=100)),
                ('proj_manager', models.CharField(max_length=100)),
                ('secret_code', models.CharField(max_length=100)),
                ('role', models.CharField(choices=[('Admin', 'Admin'), ('User', 'User')], default='User', max_length=10)),
            ],
        ),
    ]
